import type { LanguageSnippet } from "@/components/shared/app-language-tabs";

import {
    JAVASCRIPT_SNIPPET,
    PYTHON_SNIPPET,
    JAVA_SNIPPET,
    R_SNIPPET,
    C_SHARP_SNIPPET,
    CPP_SNIPPET,
    TERMINAL_SNIPPET,
    DOWNLOAD_JOB_ZIP_RESPONSE,
} from "./download-job-zip/language";

export const DOWNLOAD_JOB_ZIP = {
    method: "GET",

    path: "/api/v1/jobs/:jobId/download",

    title: "Download Job ZIP",

    description:
        "Generates a pre-signed URL for downloading all certificates generated by a completed job as a ZIP archive.",

    snippets: {
        javascript: {
            id: "javascript",
            label: "JavaScript",
            language: "typescript" as const,
            code: JAVASCRIPT_SNIPPET,
        },

        python: {
            id: "python",
            label: "Python",
            language: "python" as const,
            code: PYTHON_SNIPPET,
        },

        java: {
            id: "java",
            label: "Java",
            language: "java" as const,
            code: JAVA_SNIPPET,
        },

        r: {
            id: "r",
            label: "R",
            language: "r" as const,
            code: R_SNIPPET,
        },

        c_sharp: {
            id: "c_sharp",
            label: "C#",
            language: "csharp" as const,
            code: C_SHARP_SNIPPET,
        },

        cpp: {
            id: "cpp",
            label: "C++",
            language: "cpp" as const,
            code: CPP_SNIPPET,
        },

        terminal: {
            id: "terminal",
            label: "Terminal",
            language: "bash" as const,
            code: TERMINAL_SNIPPET,
        },
    } as Record<string, LanguageSnippet>,

    pathParameters: [
        {
            field: "jobId",
            type: "UUID",
            required: true,
            description:
                "Identifier of the completed job whose certificates should be downloaded.",
        },
    ],

    response: {
        status: 200,
        code: DOWNLOAD_JOB_ZIP_RESPONSE,
    },

    notes: [
        "The job must be completed before a ZIP can be downloaded.",
        "The returned URL is a pre-signed URL and expires after a limited time.",
        "Download the ZIP using the returned URL instead of the API endpoint.",
    ],

    errors: [
        {
            status: 400,
            title: "Bad Request",
            description: "Invalid Job ID format.",
        },
        {
            status: 401,
            title: "Unauthorized",
            description: "Missing or invalid API Key.",
        },
        {
            status: 404,
            title: "Job Not Found",
            description: "The specified job does not exist.",
        },
        {
            status: 409,
            title: "Job Not Completed",
            description: "The job has not finished processing yet.",
        },
    ],
} as const;