# ---------- Prune ----------
FROM node:22-bookworm-slim AS pruner

WORKDIR /repo

RUN npm install -g turbo

COPY . .

RUN turbo prune @certjs/api --docker


# ---------- Dependencies ----------
FROM node:22-bookworm-slim AS installer

WORKDIR /app

COPY --from=pruner /repo/out/json/ .

RUN npm ci


# ---------- Build ----------
FROM node:22-bookworm-slim AS builder

WORKDIR /app

COPY --from=installer /app .
COPY --from=pruner /repo/out/full/ .
COPY tsconfig.base.json .

RUN npm run build:packages && npm run build -w @certjs/api
# RUN npm run build:packages
# RUN npm run build --workspace=@certjs/api


# ---------- Runtime ----------
FROM node:22-bookworm-slim

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app .

EXPOSE 8080

CMD ["node","apps/api/dist/src/index.js"]
